-- Populating Customers
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Brandon', 'Moore', 'contrerasjohn@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Ryan', 'Tucker', 'garzajacqueline@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Lisa', 'Flowers', 'drivera@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Alex', 'Phillips', 'fjensen@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Charles', 'Taylor', 'annabowen@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Beverly', 'Mitchell', 'castrohailey@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Samuel', 'Lewis', 'andrewwoods@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Raven', 'Thomas', 'landerson@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Pamela', 'Benitez', 'melaniejoseph@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Joshua', 'Tucker', 'castanedaashley@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Jennifer', 'Wright', 'lchavez@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Diamond', 'Morrison', 'hdoyle@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Brenda', 'Reese', 'william55@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Dennis', 'Johnson', 'yhodges@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('William', 'Smith', 'alexandriajenkins@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Krystal', 'Delacruz', 'graydenise@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Mark', 'Peters', 'zhangnicole@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Tyler', 'Smith', 'gardneremily@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Mary', 'Roman', 'vallen@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Amanda', 'Johnson', 'hammondamanda@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Rodney', 'Miller', 'michael04@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Melissa', 'Mathews', 'christopherjackson@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Angela', 'Hamilton', 'murphyronald@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Zachary', 'Branch', 'foxtimothy@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Christopher', 'Barnett', 'kelseymoyer@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Andrew', 'Reed', 'ruizjoseph@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Daniel', 'Wagner', 'melissa46@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Michael', 'Estrada', 'davidpierce@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Ronald', 'Andrews', 'sophiaschmidt@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Jerome', 'Christensen', 'emeza@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Pamela', 'Taylor', 'lynn11@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Samantha', 'Flowers', 'moodydavid@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Samantha', 'Anderson', 'james54@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('James', 'Hernandez', 'timothysmith@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Brian', 'Collins', 'johnsonkaren@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Christopher', 'Newton', 'qhall@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Hannah', 'Williams', 'khanbrandon@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Kenneth', 'Macias', 'lpalmer@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Bobby', 'Spencer', 'kiddevan@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Daniel', 'Williams', 'qwalton@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Rebekah', 'Ellis', 'rossblake@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Gary', 'Reid', 'patricia27@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Linda', 'Dougherty', 'ramirezdavid@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Ryan', 'Wilson', 'misty44@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Kenneth', 'Smith', 'katherinefowler@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Christopher', 'Warner', 'briana13@example.com');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Jennifer', 'Harrison', 'colemanrhonda@example.org');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Joseph', 'Quinn', 'heather01@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Daniel', 'Walker', 'wilcoxkevin@example.net');
INSERT INTO Customer (FirstName, LastName, Email) VALUES ('Lindsey', 'Tran', 'smithdarren@example.net');

-- Populating Products
INSERT INTO Product (ProductName, Price) VALUES ('If Page', 61.48);
INSERT INTO Product (ProductName, Price) VALUES ('Star Week', 862.73);
INSERT INTO Product (ProductName, Price) VALUES ('As Material', 933.69);
INSERT INTO Product (ProductName, Price) VALUES ('Record Everyone', 228.51);
INSERT INTO Product (ProductName, Price) VALUES ('Development Country', 17.11);
INSERT INTO Product (ProductName, Price) VALUES ('Amount Pay', 492.06);
INSERT INTO Product (ProductName, Price) VALUES ('Dream Why', 825.0);
INSERT INTO Product (ProductName, Price) VALUES ('Car International', 549.22);
INSERT INTO Product (ProductName, Price) VALUES ('Design Cold', 552.37);
INSERT INTO Product (ProductName, Price) VALUES ('Increase Upon', 128.1);
INSERT INTO Product (ProductName, Price) VALUES ('Sit Forward', 866.35);
INSERT INTO Product (ProductName, Price) VALUES ('Station Step', 819.95);
INSERT INTO Product (ProductName, Price) VALUES ('Stage Official', 592.76);
INSERT INTO Product (ProductName, Price) VALUES ('Source Fall', 265.38);
INSERT INTO Product (ProductName, Price) VALUES ('Soldier Story', 30.5);
INSERT INTO Product (ProductName, Price) VALUES ('Off Former', 295.87);
INSERT INTO Product (ProductName, Price) VALUES ('Cause Serve', 47.7);
INSERT INTO Product (ProductName, Price) VALUES ('Must Model', 247.21);
INSERT INTO Product (ProductName, Price) VALUES ('Artist Seat', 20.6);
INSERT INTO Product (ProductName, Price) VALUES ('Staff Many', 89.93);
INSERT INTO Product (ProductName, Price) VALUES ('Allow Fly', 904.81);
INSERT INTO Product (ProductName, Price) VALUES ('According Show', 920.74);
INSERT INTO Product (ProductName, Price) VALUES ('Also Meet', 140.48);
INSERT INTO Product (ProductName, Price) VALUES ('Clearly Effort', 878.93);
INSERT INTO Product (ProductName, Price) VALUES ('Region Network', 849.96);
INSERT INTO Product (ProductName, Price) VALUES ('Impact Hope', 641.75);
INSERT INTO Product (ProductName, Price) VALUES ('Unit Seem', 825.48);
INSERT INTO Product (ProductName, Price) VALUES ('Agree Change', 52.48);
INSERT INTO Product (ProductName, Price) VALUES ('Claim Country', 46.78);
INSERT INTO Product (ProductName, Price) VALUES ('Huge Nearly', 933.67);

-- Populating PurchaseOrders
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (30, '2023-07-16');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (31, '2023-05-07');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (38, '2023-09-24');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (38, '2022-10-24');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (17, '2022-12-20');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (40, '2022-12-28');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (32, '2023-08-03');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (5, '2023-09-15');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (46, '2022-11-12');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (27, '2022-05-13');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (1, '2023-12-08');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (20, '2023-02-15');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (9, '2022-09-15');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (36, '2022-07-21');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (42, '2022-09-22');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (22, '2024-01-17');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (42, '2023-04-10');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (12, '2023-06-29');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (46, '2023-01-31');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (47, '2022-07-07');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (34, '2024-04-09');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (9, '2023-06-18');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (38, '2023-10-24');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (37, '2022-09-29');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (49, '2022-05-06');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (17, '2023-03-26');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (30, '2022-07-12');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (3, '2023-06-13');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (5, '2024-01-24');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (46, '2023-06-18');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (36, '2022-08-07');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (48, '2022-05-17');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (4, '2024-01-09');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (30, '2024-03-02');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (41, '2024-01-31');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (41, '2023-05-06');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (45, '2024-02-11');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (45, '2022-08-27');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (31, '2024-01-24');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (36, '2022-06-30');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (5, '2024-01-03');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (42, '2022-09-20');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (13, '2022-05-16');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (10, '2023-02-27');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (12, '2022-10-07');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (49, '2022-10-11');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (15, '2022-04-28');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (11, '2023-08-15');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (28, '2024-02-13');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (28, '2023-11-30');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (42, '2022-05-23');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (3, '2023-07-23');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (32, '2022-09-21');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (16, '2024-02-03');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (16, '2023-12-27');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (47, '2022-07-01');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (2, '2023-05-05');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (19, '2024-03-01');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (43, '2022-09-16');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (28, '2023-10-09');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (45, '2023-10-14');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (12, '2023-06-22');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (40, '2024-01-27');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (2, '2022-10-17');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (38, '2023-01-18');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (24, '2023-05-31');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (6, '2022-10-05');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (23, '2024-01-07');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (31, '2023-11-05');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (16, '2023-04-29');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (21, '2024-01-05');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (36, '2023-06-29');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (41, '2023-04-20');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (22, '2022-05-11');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (43, '2023-11-21');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (3, '2023-08-02');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (15, '2022-12-08');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (42, '2024-03-09');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (24, '2022-07-18');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (31, '2022-08-02');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (1, '2022-07-05');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (7, '2023-08-25');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (26, '2023-07-02');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (46, '2024-01-09');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (45, '2022-08-13');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (37, '2022-10-26');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (27, '2024-03-14');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (40, '2024-04-11');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (31, '2023-07-06');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (30, '2023-03-11');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (29, '2023-05-03');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (23, '2022-12-13');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (15, '2023-11-18');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (44, '2023-09-08');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (6, '2023-10-16');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (3, '2022-09-22');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (34, '2022-05-02');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (39, '2022-06-21');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (43, '2022-10-02');
INSERT INTO PurchaseOrder (CustomerID, OrderDate) VALUES (41, '2024-03-10');

-- Populating OrderDetails
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (28, 11, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (73, 24, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (69, 13, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (55, 13, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (91, 21, 18);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (21, 29, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (83, 30, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (75, 29, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (1, 22, 1);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (73, 16, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (83, 28, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (17, 4, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (42, 11, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (75, 16, 19);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (2, 3, 2);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (72, 19, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (87, 2, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (43, 27, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (65, 4, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (34, 18, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (79, 1, 12);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (97, 4, 20);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (99, 18, 2);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (39, 22, 20);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (13, 27, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (3, 26, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (48, 30, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (37, 25, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (66, 8, 3);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (89, 4, 20);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (57, 2, 1);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (51, 16, 9);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (14, 29, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (25, 22, 12);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (31, 12, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (71, 20, 3);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (25, 24, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (86, 21, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (72, 4, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (94, 23, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (86, 23, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (11, 11, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (8, 4, 2);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (86, 6, 19);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (5, 15, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (65, 7, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (83, 11, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (26, 2, 19);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (45, 9, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (21, 24, 19);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (55, 26, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (50, 19, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (3, 8, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (17, 25, 5);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (6, 16, 2);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (9, 16, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (25, 16, 19);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (65, 24, 1);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (33, 19, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (25, 27, 1);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (19, 26, 3);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (69, 17, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (28, 8, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (43, 19, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (6, 21, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (29, 24, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (91, 20, 3);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (25, 10, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (21, 16, 9);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (90, 9, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (98, 10, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (64, 27, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (21, 13, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (15, 19, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (36, 25, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (89, 15, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (55, 20, 20);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (46, 15, 20);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (59, 27, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (54, 3, 12);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (29, 8, 16);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (39, 23, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (50, 12, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (22, 23, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (48, 14, 19);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (32, 23, 16);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (60, 23, 2);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (45, 12, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (67, 27, 5);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (11, 14, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (39, 8, 16);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (100, 13, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (39, 3, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (50, 21, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (18, 23, 20);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (93, 30, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (100, 2, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (70, 5, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (83, 28, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (5, 27, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (80, 24, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (4, 21, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (96, 28, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (9, 20, 20);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (46, 12, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (75, 14, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (65, 14, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (41, 5, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (70, 12, 12);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (51, 17, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (78, 25, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (51, 21, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (64, 8, 1);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (36, 1, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (55, 9, 16);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (19, 10, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (47, 5, 9);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (63, 24, 12);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (87, 10, 5);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (95, 28, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (38, 7, 2);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (3, 3, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (75, 10, 16);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (40, 23, 1);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (6, 29, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (82, 23, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (44, 25, 16);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (5, 24, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (92, 27, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (2, 20, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (70, 14, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (68, 11, 9);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (26, 23, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (19, 24, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (9, 26, 1);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (56, 11, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (18, 24, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (93, 7, 1);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (16, 16, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (87, 28, 1);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (9, 4, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (75, 15, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (39, 17, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (9, 18, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (16, 23, 2);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (78, 19, 19);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (48, 16, 20);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (10, 4, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (44, 13, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (87, 9, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (87, 1, 16);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (93, 13, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (90, 1, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (32, 13, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (38, 17, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (1, 1, 18);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (21, 7, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (41, 25, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (29, 12, 19);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (21, 22, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (10, 14, 10);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (89, 24, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (23, 4, 3);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (48, 27, 9);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (33, 24, 9);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (64, 21, 5);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (15, 10, 18);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (24, 9, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (24, 20, 2);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (4, 13, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (49, 3, 18);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (72, 23, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (56, 12, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (32, 4, 18);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (60, 13, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (48, 5, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (2, 27, 5);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (70, 3, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (91, 21, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (89, 2, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (60, 8, 13);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (29, 16, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (31, 23, 11);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (16, 11, 7);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (51, 15, 4);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (85, 22, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (23, 7, 6);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (38, 15, 12);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (60, 15, 17);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (49, 6, 15);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (3, 23, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (61, 9, 19);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (70, 21, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (90, 15, 14);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (68, 14, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (5, 7, 8);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (62, 1, 16);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (23, 13, 9);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (10, 24, 20);
INSERT INTO OrderDetail (OrderID, ProductID, Quantity) VALUES (63, 17, 1);
